/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ASUS
 */
public class Cetak_Faktur extends javax.swing.JFrame {

    /**
     * Creates new form Cetak_Faktur
     */
    public Cetak_Faktur() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        no_pembelian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("CETAK DATA PEMBELIAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setText("No pembelian :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));
        jPanel1.add(no_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 440));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Print.png"))); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 90, -1));

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String pembelian = no_pembelian.getText();  // TODO add your handling code here:
         try{
          Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection
("jdbc:mysql://127.0.0.1/penjualan_db", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="select * from tb_pembelian where "+ "no_pembelian='" + no_pembelian.getText()
+"'";
 ResultSet rs = statement.executeQuery(sql);
            if (rs.next()){
              jTextArea1.setText("                       *** STRUK FROM VINYARD ***"+
                                 "\n     Jl.Orange County Boulevard, Cibatu,. Kab.Bekasi 17530"+
                                 "\n                                  Telp.(0881)025581707"+
                                 "\n============================================"+
                                 "\n=========TRANSAKSI PEMBELIAN WINE==========" + "\n" 
                                         + "No Pembelian                        : " + rs.getString(1)+ "\n" 
                                         + "No faktur                                  : " + rs.getString(2)+ "\n" 
                                         + "Tanggal                                   : " + rs.getString(3)+ "\n"
                                         + "Jam                                          : " + rs.getString(4)+ "\n"
                                         + "Kode Pembeli                        : " + rs.getString(5) +"\n"
                                         + "Nama Pembeli                      : " + rs.getString(6) +"\n"        
                                         + "Kode Penjual                         : " + rs.getString(7) +"\n"
                                         + "Nama Penjual                       : " + rs.getString(8) +"\n"
                                         + "Kode Wine                             : " + rs.getString(9) +"\n"
                                         + "Nama Wine                           : " + rs.getString(10) +"\n"
                                         + "Merk\t                    : " + rs.getString(11) +"\n"
                                         + "Warna\t                    : " + rs.getString(12) +"\n"
                                         + "Tahun\t                    : " + rs.getString(13) +"\n"
                                         + "Harga\t                    : " + rs.getString(14) +"\n"
                                         +
                                
                                 "\n============================================"+
                                 "\n    Terimasih Telah Memakai Jasa Layanan Kami,"+
                                 "\n          Demi Kenyamanan Pelanggan Dimohon."+
                                 "\n        Mengecek Dulu Barang Yang Sudah Di Beli."+
                                 "\n");
              }else{
            JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
            jTextArea1.setText("");
            no_pembelian.setText("");
            statement.close();
            koneksi.close();
        }
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan"+ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        JasperReport jr;
 JasperPrint jp;
 com.mysql.jdbc.Statement st;
 ResultSet rs=null;
 String sql;
 try{
 try{
 st = (com.mysql.jdbc.Statement) Koneksi.getKoneksi().createStatement();
 sql = "SELECT * from tb_pembelian";
 st.execute(sql);
 rs = st.getResultSet();
 } catch (SQLException e){}
 jr = JasperCompileManager.compileReport("D:\\UASPBO\\UAS_VINYARD\\src\\Laporan\\Cetak_Faktur.jrxml");
 jp =JasperFillManager.fillReport(jr, new HashMap(),new JRResultSetDataSource(rs));
 JasperViewer.viewReport(jp,false);
 }catch (JRException e){
 JOptionPane.showMessageDialog(this, e.getMessage());
 }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
           int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin mau Keluar ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Form_Utama_Admin().show();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cetak_Faktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cetak_Faktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cetak_Faktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cetak_Faktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cetak_Faktur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField no_pembelian;
    // End of variables declaration//GEN-END:variables
}
