/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Form_Utama_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Form_Utama_Admin
     */
    public Form_Utama_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BuatFaktur = new javax.swing.JMenuItem();
        CekFaktur = new javax.swing.JMenuItem();
        DataPembeli = new javax.swing.JMenuItem();
        DataPenjual = new javax.swing.JMenuItem();
        DataPenjualan = new javax.swing.JMenuItem();
        DataPembelian = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        KELUAR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logo v.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 270));

        jMenu1.setText("FITUR ADMIN");

        BuatFaktur.setText("Buat Faktur Pembelian");
        BuatFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuatFakturActionPerformed(evt);
            }
        });
        jMenu1.add(BuatFaktur);

        CekFaktur.setText("Cek Faktur");
        CekFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekFakturActionPerformed(evt);
            }
        });
        jMenu1.add(CekFaktur);

        DataPembeli.setText("Cetak Data Pembeli");
        DataPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPembeliActionPerformed(evt);
            }
        });
        jMenu1.add(DataPembeli);

        DataPenjual.setText("Cetak Data Penjual");
        DataPenjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPenjualActionPerformed(evt);
            }
        });
        jMenu1.add(DataPenjual);

        DataPenjualan.setText("Cetak Data Penjualan");
        DataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(DataPenjualan);

        DataPembelian.setText("Cetak Data Pembelian");
        DataPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPembelianActionPerformed(evt);
            }
        });
        jMenu1.add(DataPembelian);

        jMenuItem1.setText("Cetak Faktur Pembelian");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("KELUAR");

        KELUAR.setText("KELUAR");
        KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUARActionPerformed(evt);
            }
        });
        jMenu2.add(KELUAR);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPembeliActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Cetak Data Pembeli ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Cetak_Data_Pembeli().show();
    }//GEN-LAST:event_DataPembeliActionPerformed

    private void BuatFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuatFakturActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Buat Faktur Pembelian ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Form_Faktur().show();
    }//GEN-LAST:event_BuatFakturActionPerformed

    private void CekFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekFakturActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Cek Data Faktur ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Cek_Faktur().show();
    }//GEN-LAST:event_CekFakturActionPerformed

    private void DataPenjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPenjualActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Cetak Data Penjual ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Cetak_Data_Penjual().show();
    }//GEN-LAST:event_DataPenjualActionPerformed

    private void DataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPenjualanActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Cetak Data Penjualan ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Cetak_Data_Penjualan().show();
    }//GEN-LAST:event_DataPenjualanActionPerformed

    private void DataPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPembelianActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Cetak Data Pembelian ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Cetak_Data_Pembelian().show();
    }//GEN-LAST:event_DataPembelianActionPerformed

    private void KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUARActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin mau Keluar ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new TAMPILAN().show();
    }//GEN-LAST:event_KELUARActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Cetak Faktur Pembelian ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Cek_Faktur().show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Utama_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuatFaktur;
    private javax.swing.JMenuItem CekFaktur;
    private javax.swing.JMenuItem DataPembeli;
    private javax.swing.JMenuItem DataPembelian;
    private javax.swing.JMenuItem DataPenjual;
    private javax.swing.JMenuItem DataPenjualan;
    private javax.swing.JMenuItem KELUAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
