/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
/**
 *
 * @author ASUS
 */
public class Form_Utama_Member extends javax.swing.JFrame {

    /**
     * Creates new form Form_Menu_Utama
     */
    public Form_Utama_Member() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Form_Pembeli = new javax.swing.JMenuItem();
        Form_Penjual = new javax.swing.JMenuItem();
        Form_Pembelian = new javax.swing.JMenuItem();
        Form_Penjualan = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenu();
        Form_keluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logo v.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 270));

        jMenu1.setText("FITUR MEMBER");

        Form_Pembeli.setText("Form Pembeli");
        Form_Pembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_PembeliActionPerformed(evt);
            }
        });
        jMenu1.add(Form_Pembeli);

        Form_Penjual.setText("Form Penjual");
        Form_Penjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_PenjualActionPerformed(evt);
            }
        });
        jMenu1.add(Form_Penjual);

        Form_Pembelian.setText("Form Transaksi Pembelian");
        Form_Pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_PembelianActionPerformed(evt);
            }
        });
        jMenu1.add(Form_Pembelian);

        Form_Penjualan.setText("Form Penjualan");
        Form_Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_PenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(Form_Penjualan);

        jMenuBar1.add(jMenu1);

        Keluar.setText("KELUAR");

        Form_keluar.setText("KELUAR");
        Form_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_keluarActionPerformed(evt);
            }
        });
        Keluar.add(Form_keluar);

        jMenuBar1.add(Keluar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Form_PenjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_PenjualActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin isi Formulir ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Form_Penjual().show();
    }//GEN-LAST:event_Form_PenjualActionPerformed

    private void Form_PembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_PembeliActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin isi Formulir ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Form_Pembeli().show();
    }//GEN-LAST:event_Form_PembeliActionPerformed

    private void Form_PembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_PembelianActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin isi Form Pembelian ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Form_Pembelian().show();
    }//GEN-LAST:event_Form_PembelianActionPerformed

    private void Form_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_keluarActionPerformed
        // TODO add your handling code here:
  int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin mau Keluar ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new TAMPILAN().show();
    }//GEN-LAST:event_Form_keluarActionPerformed

    private void Form_PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_PenjualanActionPerformed
        // TODO add your handling code here:
        int jawab = javax.swing.JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin isi Form Penjualan ?", "Konfirmasi",javax.swing.JOptionPane.YES_NO_OPTION);
        if(jawab==0)this.dispose();
        new Form_Penjualan().show();
    }//GEN-LAST:event_Form_PenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Utama_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Utama_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Form_Pembeli;
    private javax.swing.JMenuItem Form_Pembelian;
    private javax.swing.JMenuItem Form_Penjual;
    private javax.swing.JMenuItem Form_Penjualan;
    private javax.swing.JMenuItem Form_keluar;
    private javax.swing.JMenu Keluar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
